version: '3.8'

services:
  happy_stt:
    build: .
    container_name: happy_stt
    network_mode: host           # UDP通信のため必須
    ipc: host                    # （オプション）共有メモリを使う場合に必要
    devices:
      - "/dev/snd:/dev/snd"
    volumes:
      - .:/workspace
      - /home/daniil/main_ws:/opt/hm_msgs_ws
    environment:
      - ROS_DOMAIN_ID=0
      - FASTRTPS_DEFAULT_PROFILES_FILE=/workspace/fastrtps_profile.xml
    stdin_open: true
    tty: true
